### ISSUE TITLE
Windows 10, VSCode, not enough values to unpack error in latest release with UNC path

### ISSUE THREAD

**Issue by JSkier21** [StamusNetworks/suricata-language-server#4]
Hi Eric,

Works great in Linux, however running into this error in Windows 10, VSCode below when using a UNC path (ie \\server\share\rule.rules). From what I can tell, I think it's an issue with jsonrpc specifically (I can put in an issue over there if that makes sense to you). 

I will put a PR in shortly to note this in the README. 

Basically, any UNC paths get treated as file:///server/share/rule.rules. 

The **workaround** is to use a mapped drive letter reference to open the file (or folder with rules in it). X:\Rules\rule.rules, instead of the UNC path. This works as expected. 

**Screenshot:**
![image](https://user-images.githubusercontent.com/3190223/149403592-6ef0bb1c-a1b1-4151-9e1b-365286c8f590.png)

**Traceback:**
`Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\suricatals\langserver.py", line 99, in handle
    handler(request)
  File "C:\Python310\lib\site-packages\suricatals\langserver.py", line 322, in serve_onSave
    filepath = path_from_uri(uri)
  File "C:\Python310\lib\site-packages\suricatals\jsonrpc.py", line 24, in path_from_uri
    _, path = uri.split("file:///", 1)
ValueError: not enough values to unpack (expected 2, got 1)`

**Comment by regit** [comment]
Thanks for the bug report. I'm going to try to fix this.

**Comment by regit** [comment]
@JSkier21 could you confirm that v0.5.1 is fixing the problem in your case ?

**Comment by JSkier21** [comment]
Confirmed working with reference to UNC path. Thank you @regit for fixing so quickly!
